#!/usr/bin/env python3
import argparse
import json
import time
import random
import re
from pathlib import Path
from typing import Any, Dict, List, Tuple, Optional

import numpy as np
import torch
from datasets import load_dataset, Dataset
from tqdm import tqdm
from transformers import AutoTokenizer
from vllm import LLM, SamplingParams
from vllm.sampling_params import GuidedDecodingParams
import math
from pydantic import BaseModel, Field


# --------------------------
# Utilities
# --------------------------

def set_seed(seed: int = 5775709):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)


def parse_arguments():
    parser = argparse.ArgumentParser()
    # Data and models
    parser.add_argument("--dataset_repo", type=str, default="zjhhhh/Qwen2.5_3B_generation", help="Hugging Face dataset repo id (split=train)")
    parser.add_argument("--base_model", type=str, default="Qwen/Qwen2.5-3B-Instruct", help="Model id/path to sample base responses")
    parser.add_argument("--check_points", type=str, nargs='+', default=["Qwen/Qwen2.5-3B-Instruct"], help="One or more model ids/paths to evaluate")
    parser.add_argument("--output_repo_prefix", type=str, required=True, help="Prefix for output repo; final repo is {prefix}_{model_name}")

    # Generation
    parser.add_argument("--n_response", type=int, default=2, help="Number of responses to sample per prompt for base/model")
    parser.add_argument("--maxlen", type=int, default=8192)
    parser.add_argument("--world_size", type=int, default=4)
    parser.add_argument("--temperature", type=float, default=0.1)
    parser.add_argument("--top_p", type=float, default=0.9)
    parser.add_argument("--start_idx", type=int, default=0)
    parser.add_argument("--end_idx", type=int, default=-1)

    # Judge
    parser.add_argument("--judge_model", type=str, required=True, help="Model id/path for the local judge LLM")
    parser.add_argument("--n_judge_samples", type=int, default=5)
    parser.add_argument("--judge_temperature", type=float, default=0.6, help="Sampling temperature for the judge model")
    parser.add_argument("--judge_top_p", type=float, default=0.95, help="Top-p nucleus sampling for the judge model")
    parser.add_argument("--judge_top_k", type=int, default=20, help="Top-k sampling value for the judge model")
    parser.add_argument("--judge_max_tokens", type=int, default=256, help="Maximum tokens generated by the judge model")
    parser.add_argument(
        "--switch_position",
        action="store_true",
        default=False,
        help="Also judge with responses swapped (B vs A) and reverse the resulting scores",
    )
    parser.add_argument(
        "--score_json_path",
        type=str,
        default=None,
        help="Optional explicit path for the JSON score summary",
    )

    # Scoring
    parser.add_argument("--beta", type=float, default=1.0)

    # Debug
    parser.add_argument("--max_prompts", type=int, default=None, help="Optional cap on number of unique prompts for testing")

    return parser.parse_args()


def get_message(instruction: str) -> List[Dict[str, str]]:
    return [{"role": "user", "content": instruction}]


def sanitize_model_name(model_id: str) -> str:
    return model_id.strip().replace("/", "__").replace(" ", "_")


def split_requirements_to_checks(dataset: Dataset) -> Dataset:
    expanded = []
    for row in dataset:
        requirements_str: str = row.get("requirements", "")
        if not requirements_str:
            # Fallback: if no structured requirements, keep a single "check" equal to prompt
            expanded.append({
                "prompt": row["prompt"],
                "requirements": requirements_str,
                "check": row["prompt"],
                "importance": None,
            })
            continue

        counter = 1
        parts: List[str] = []
        remaining = requirements_str
        while len(remaining) > 0:
            assert remaining.startswith(f"{counter})"), f"Malformed requirements at counter {counter}: {remaining[:80]}"
            needle = f"/100)\n{counter+1})"
            pos = remaining.find(needle)
            if pos > 0:
                curr = remaining[len(f"{counter})"):pos + len("/100)\n")]
            else:
                curr = remaining[len(f"{counter})"):]
            parts.append(curr)
            remaining = remaining[len(curr) + len(f"{counter})"):]
            counter += 1

        parts = list(map(lambda s: s.strip(), parts))
        for chunk in parts:
            base_fields = {
                "prompt": row["prompt"],
                "requirements": requirements_str,
            }
            if "(importance:" in chunk:
                check_text = chunk.split("(importance:")[0].strip()
                try:
                    importance_val = int(chunk.split("(importance:")[1].split("/")[0].strip())
                except Exception:
                    importance_val = None
                expanded.append({**base_fields, "check": check_text, "importance": importance_val})
            else:
                expanded.append({**base_fields, "check": chunk, "importance": None})

    return Dataset.from_list(expanded)


def load_preference_5score_template() -> str:
    template_path = Path(__file__).parent / "prompt_preference_5score.txt"
    with open(template_path, 'r') as f:
        return f.read()


def get_numeric_mode(values: List[int], score_range: Tuple[int, int]) -> int:
    if not values:
        return None
    min_score, max_score = score_range
    filtered = [int(v) for v in values if min_score <= int(v) <= max_score]
    if not filtered:
        return None
    from collections import Counter
    counts = Counter(filtered)
    max_count = max(counts.values())
    modes = [k for k, v in counts.items() if v == max_count]
    modes.sort()
    return modes[len(modes) // 2]


class Preference5ScoreOutput(BaseModel):
    explanation: str
    verdict: int = Field(ge=-1, le=4)


PREFERENCE_5SCORE_GUIDED_DECODING = GuidedDecodingParams(json=Preference5ScoreOutput.model_json_schema())


def is_valid_5score(value: Optional[int]) -> bool:
    try:
        if value is None:
            return False
        v = int(value)
        return -1 <= v <= 4
    except Exception:
        return False


def reverse_score_5score(score: int) -> int:
    if score == -1:
        return -1
    return 4 - int(score)


def parse_verdict_safely(text: str) -> Optional[int]:
    if not text:
        return None
    try:
        obj = json.loads(text)
        if isinstance(obj, dict):
            value = obj.get("verdict")
        else:
            value = obj
        if is_valid_5score(value):
            return int(value)
    except Exception:
        pass

    match = re.search(r"verdict\s*[:=]\s*([-]?\d)", text, flags=re.IGNORECASE)
    if match:
        try:
            cand = int(match.group(1))
            return cand if is_valid_5score(cand) else None
        except Exception:
            pass

    match = re.search(r"\b([-]?\d)\b", text)
    if match:
        try:
            cand = int(match.group(1))
            return cand if is_valid_5score(cand) else None
        except Exception:
            pass
    return None


def aggregate_numeric_samples(samples: List[int]) -> Tuple[Optional[float], Optional[int]]:
    parsed = [int(s) for s in samples if is_valid_5score(s)]
    if not parsed:
        return None, None
    valid_for_mean = [x for x in parsed if x != -1]
    mean_val = (sum(valid_for_mean) / len(valid_for_mean)) if valid_for_mean else None
    majority_val = get_numeric_mode(parsed, (0, 4))
    return mean_val, majority_val


def _collect_normalized_scores(value: Any) -> List[float]:
    if value is None:
        return []
    if isinstance(value, (list, tuple)):
        normalized: List[float] = []
        for item in value:
            normalized.extend(_collect_normalized_scores(item))
        return normalized
    try:
        return [float(value) / 4]
    except Exception:
        return []
def generate_n_responses(model_id: str, prompts: List[str], world_size: int, maxlen: int, n_response: int, temperature: float, top_p: float) -> List[List[str]]:
    print(f"Generating {n_response} responses per prompt with model: {model_id}")
    tokenizer = AutoTokenizer.from_pretrained(model_id)
    llm = LLM(
        model=model_id,
        tensor_parallel_size=world_size,
        max_model_len=maxlen,
        gpu_memory_utilization=0.85,
        trust_remote_code=True,
    )
    chat_prompts = [tokenizer.apply_chat_template([{ "role": "user", "content": p }], tokenize=False, add_generation_prompt=True) for p in tqdm(prompts)]

    all_pass_outputs: List[List[str]] = []  # shape [n_response][num_prompts]
    for i in range(n_response):
        set_seed(i * 50)
        params = SamplingParams(
            temperature=temperature,
            top_p=top_p,
            max_tokens=maxlen,
            seed=i * 50,
        )
        outputs = llm.generate(chat_prompts, params)
        texts = [o.outputs[0].text for o in outputs]
        all_pass_outputs.append(texts)

    # transpose -> [num_prompts][n_response]
    per_prompt: List[List[str]] = []
    for idx in range(len(prompts)):
        per_prompt.append([all_pass_outputs[j][idx] for j in range(n_response)])
    del llm
    del tokenizer
    torch.cuda.empty_cache()
    return per_prompt


def add_static_response_columns(dataset: Dataset, rows: List[dict], prompt_to_idx: Dict[str, int], base_resps: List[List[str]], model_resps: List[List[str]]):
    num_rows = len(rows)
    n_base = len(base_resps[0]) if base_resps else 0
    n_model = len(model_resps[0]) if model_resps else 0
    # Base responses
    for i in range(n_base):
        col = [base_resps[prompt_to_idx[rows[r]["prompt"]]][i] for r in range(num_rows)]
        dataset = dataset.add_column(f"base_response_{i}", col)
    # Model responses
    for j in range(n_model):
        col = [model_resps[prompt_to_idx[rows[r]["prompt"]]][j] for r in range(num_rows)]
        dataset = dataset.add_column(f"model_response_{j}", col)
    return dataset


def parse_preference_choice(s: str) -> str:
    if s is None:
        return None
    t = s.strip()
    if not t:
        return None
    u = t.upper()
    if u in ("A", "B"):
        return u
    # Fallback: pick first occurrence of A/B
    for ch in u:
        if ch in ("A", "B"):
            return ch
    return None


def aggregate_binary_choice(raw_samples: List[str]) -> str:
    # Return majority of 'A'/'B'; None if undecided
    choices = [parse_preference_choice(s) for s in raw_samples if s is not None]
    choices = [c for c in choices if c in ("A", "B")]
    if not choices:
        return None
    from collections import Counter
    counts = Counter(choices)
    if counts.get("A", 0) > counts.get("B", 0):
        return "A"
    if counts.get("B", 0) > counts.get("A", 0):
        return "B"
    return None


def merge_dataset_results(dataset: Dataset) -> Dataset:
    """Merge rows by prompt, aggregating judge columns into lists.

    Keeps scalar fields per prompt: prompt, requirements, base_response_*, model_response_*.
    Aggregates all columns starting with 'judge_' and ending with '_majority' or '_mean' into lists.
    """
    merged: Dict[str, dict] = {}
    for row in dataset:
        prompt = row["prompt"]
        if prompt not in merged:
            base_fields = {}
            # Keep scalar fields
            for key, value in row.items():
                if key == "prompt" or key == "requirements" or key.startswith("base_response_") or key.startswith("model_response_"):
                    base_fields[key] = value
            # Initialize judge lists for any judge columns present in this row
            for key in row.keys():
                if key.startswith("judge_") and (key.endswith("_majority") or key.endswith("_mean")):
                    base_fields[key] = []
            merged[prompt] = base_fields

        # Append judge values (skip None)
        for key, value in row.items():
            if key.startswith("judge_") and (key.endswith("_majority") or key.endswith("_mean")):
                if key not in merged[prompt]:
                    merged[prompt][key] = []
                if value is not None:
                    merged[prompt][key].append(value)

    return Dataset.from_list(list(merged.values()))


def score_dataset(ds: Dataset, beta: float) -> float:
    # Determine counts
    base_cols = sorted([c for c in ds.column_names if c.startswith("base_response_")], key=lambda x: int(x.split("_")[-1]))
    model_cols = sorted([c for c in ds.column_names if c.startswith("model_response_")], key=lambda x: int(x.split("_")[-1]))
    n_base = len(base_cols)
    n_model = len(model_cols)

    # Group rows by prompt
    grouped: Dict[str, List[dict]] = {}
    for row in ds:
        p = row["prompt"]
        grouped.setdefault(p, []).append(row)

    prompt_vals: List[float] = []
    for p, rows in grouped.items():
        # For each base response y' index b, compute P(x,y')
        exp_terms: List[float] = []
        for b in range(n_base):
            # For each check row: average over model responses a of judge_{a}_{b}
            per_check_avgs: List[float] = []
            for row in rows:
                vals: List[float] = []
                # Prefer mean; fallback to majority
                for a in range(n_model):
                    mean_key = f"judge_{a}_{b}_mean"
                    maj_key = f"judge_{a}_{b}_majority"
                    values = _collect_normalized_scores(row.get(mean_key, None))
                    if not values:
                        values = _collect_normalized_scores(row.get(maj_key, None))
                    if values:
                        vals.extend(values)
                if vals:
                    per_check_avgs.append(sum(vals) / len(vals))
            if per_check_avgs:
                P_xy = min(per_check_avgs)
                exp_terms.append(math.exp(-P_xy / beta))
        if exp_terms:
            prompt_vals.append(sum(exp_terms) / len(exp_terms))

    if not prompt_vals:
        return float('nan')

    return -beta * (sum(prompt_vals) / len(prompt_vals))


def score(repo_id: str, beta: float) -> float:
    try:
        ds = load_dataset(repo_id, split='test')
    except Exception:
        ds = load_dataset(repo_id, split='train')
    return score_dataset(ds, beta)


def main():
    st = time.time()
    args = parse_arguments()

    # Load dataset and expand to (prompt, check)
    try:
        raw = load_dataset(args.dataset_repo, split='test')
    except Exception:
        raw = load_dataset(args.dataset_repo, split='train')
    if args.end_idx != -1:
        raw = raw.select(range(args.start_idx, min(args.end_idx, len(raw))))
    expanded = split_requirements_to_checks(raw)

    # Prepare unique prompts
    unique_prompts: List[str] = list(dict.fromkeys([row["prompt"] for row in expanded]))
    if args.max_prompts is not None:
        unique_prompts = unique_prompts[: args.max_prompts]
        expanded = Dataset.from_list([row for row in expanded if row["prompt"] in set(unique_prompts)])
    prompt_to_idx: Dict[str, int] = {p: i for i, p in enumerate(unique_prompts)}

    print(f"Num expanded rows (prompt, check): {len(expanded)}")
    print(f"Num unique prompts: {len(unique_prompts)}")

    # Generate base responses once
    base_resps = generate_n_responses(
        args.base_model,
        unique_prompts,
        args.world_size,
        args.maxlen,
        args.n_response,
        args.temperature,
        args.top_p,
    )

    # Load judge template
    template = load_preference_5score_template()

    # Iterate over candidate models
    expanded_rows = [row for row in expanded]
    scores_accumulator: List[float] = []
    for model_id in args.check_points:
        model_name = sanitize_model_name(model_id.split(":")[0])
        print(f"\n=== Evaluating {model_name} ===")

        # Generate candidate model responses
        model_resps = generate_n_responses(
            model_id,
            unique_prompts,
            args.world_size,
            args.maxlen,
            args.n_response,
            args.temperature,
            args.top_p,
        )

        # Instantiate the judge model once per checkpoint
        judge_tokenizer = AutoTokenizer.from_pretrained(args.judge_model)
        judge_llm = LLM(
            model=args.judge_model,
            tensor_parallel_size=args.world_size,
            max_model_len=args.maxlen,
            gpu_memory_utilization=0.85,
            trust_remote_code=True,
        )

        sampling_params = SamplingParams(
            temperature=args.judge_temperature,
            top_p=args.judge_top_p,
            top_k=args.judge_top_k,
            n=args.n_judge_samples,
            max_tokens=args.judge_max_tokens,
            guided_decoding=PREFERENCE_5SCORE_GUIDED_DECODING,
        )

        num_rows = len(expanded_rows)
        n_base = len(base_resps[0]) if base_resps else 0
        n_model = len(model_resps[0]) if model_resps else 0

        mean_cols: Dict[Tuple[int, int], List[Optional[float]]] = {}
        maj_cols: Dict[Tuple[int, int], List[Optional[int]]] = {}
        for ai in range(n_model):
            for bj in range(n_base):
                mean_cols[(ai, bj)] = [None] * num_rows
                maj_cols[(ai, bj)] = [None] * num_rows

        for ai in range(n_model):
            for bj in range(n_base):
                rendered_prompts = []
                for row in expanded_rows:
                    p = row["prompt"]
                    check = row.get("check", p)
                    pid = prompt_to_idx[p]
                    a_text = model_resps[pid][ai]
                    b_text = base_resps[pid][bj]
                    instruction = template.format(prompt=p, response_a=a_text, response_b=b_text, check=check)
                    chat = get_message(instruction)
                    rendered_prompts.append(
                        judge_tokenizer.apply_chat_template(chat, tokenize=False, add_generation_prompt=True)
                    )

                response = judge_llm.generate(rendered_prompts, sampling_params)
                all_samples: List[List[int]] = []
                for result in response:
                    verdicts = [parse_verdict_safely(candidate.text) for candidate in result.outputs]
                    filtered = [int(v) for v in verdicts if is_valid_5score(v)]
                    all_samples.append(filtered)

                if args.switch_position:
                    rendered_switched = []
                    for row in expanded_rows:
                        p = row["prompt"]
                        check = row.get("check", p)
                        pid = prompt_to_idx[p]
                        a_text = base_resps[pid][bj]
                        b_text = model_resps[pid][ai]
                        instruction = template.format(prompt=p, response_a=a_text, response_b=b_text, check=check)
                        chat = get_message(instruction)
                        rendered_switched.append(
                            judge_tokenizer.apply_chat_template(chat, tokenize=False, add_generation_prompt=True)
                        )

                    response_switched = judge_llm.generate(rendered_switched, sampling_params)
                    for idx_row, result_switched in enumerate(response_switched):
                        verdicts = [parse_verdict_safely(candidate.text) for candidate in result_switched.outputs]
                        filtered = [int(v) for v in verdicts if is_valid_5score(v)]
                        reversed_scores = [reverse_score_5score(v) for v in filtered]
                        if idx_row < len(all_samples):
                            all_samples[idx_row].extend(reversed_scores)
                        else:
                            all_samples.append(reversed_scores)
                    del response_switched
                    torch.cuda.empty_cache()

                for row_idx, scores in enumerate(all_samples):
                    mean_val, maj_val = aggregate_numeric_samples(scores)
                    mean_cols[(ai, bj)][row_idx] = mean_val
                    maj_cols[(ai, bj)][row_idx] = maj_val

                del response
                torch.cuda.empty_cache()

        try:
            del judge_llm
        except Exception:
            pass
        try:
            del judge_tokenizer
        except Exception:
            pass
        torch.cuda.empty_cache()

        # Build dataset to push: start from expanded
        ds = expanded
        ds = add_static_response_columns(ds, expanded_rows, prompt_to_idx, base_resps, model_resps)
        for (ai, bj), col in maj_cols.items():
            ds = ds.add_column(f"judge_{ai}_{bj}_majority", col)
        for (ai, bj), col in mean_cols.items():
            ds = ds.add_column(f"judge_{ai}_{bj}_mean", col)

        result = score_dataset(ds, args.beta)

        # Push to hub
        repo_id = f"{args.output_repo_prefix}_{model_name}"

        # Also push merged-by-prompt dataset with judge scores saved as lists
        ds_merged = merge_dataset_results(ds)
        merged_repo_id = f"{args.output_repo_prefix}_{model_name}"
        print(f"Pushing merged results to {merged_repo_id} ...")
        ds_merged.push_to_hub(merged_repo_id)

        # Score (placeholder)
        print(f"Score for {model_name}: {result}")
        scores_accumulator.append(result)

    print(f"Done. Total time: {time.time() - st:.2f}s")

    summary_path = Path(args.score_json_path) if args.score_json_path else Path(f"{sanitize_model_name(args.output_repo_prefix)}_scores.json")
    summary_data = {"checkpoints": args.check_points, "scores": scores_accumulator}
    with open(summary_path, "w") as f:
        json.dump(summary_data, f, indent=2)
    print(f"Saved score summary to {summary_path}")


if __name__ == "__main__":
    main()
