#!/usr/bin/env python3
import os
import argparse
import json
import time
import random
import re
import math
from pathlib import Path
from typing import Any, Dict, List, Tuple, Optional
import multiprocessing as mp


# --------------------------
# Utilities (GPU-heavy imports happen inside functions)
# --------------------------

# Ensure consistent GPU indexing across heterogeneous devices; avoids device mix-ups
os.environ.setdefault("CUDA_DEVICE_ORDER", "PCI_BUS_ID")
# Avoid tokenizers thread pool issues after process spawning
os.environ.setdefault("TOKENIZERS_PARALLELISM", "false")


def set_seed(seed: int = 5775709):
    random.seed(seed)
    try:
        import numpy as np

        np.random.seed(seed)
    except Exception:
        pass
    try:
        import torch

        torch.manual_seed(seed)
        torch.cuda.manual_seed_all(seed)
    except Exception:
        pass


def parse_arguments():
    parser = argparse.ArgumentParser()
    # Data and models
    parser.add_argument("--dataset_repo", type=str, default="zjhhhh/Qwen2.5_3B_generation", help="Hugging Face dataset repo id (split=train)")
    parser.add_argument("--base_model", type=str, default="Qwen/Qwen2.5-3B-Instruct", help="Model id/path to sample base responses")
    parser.add_argument("--check_points", type=str, nargs='+', default=["Qwen/Qwen2.5-3B-Instruct"], help="One or more model ids/paths to evaluate")
    parser.add_argument("--output_repo_prefix", type=str, required=True, help="Prefix for output repo; final repo is {prefix}_{model_name}")

    # Generation
    parser.add_argument("--n_response", type=int, default=2, help="Number of responses to sample per prompt for base/model")
    parser.add_argument("--maxlen", type=int, default=8192)
    parser.add_argument("--base_world_size", type=int, default=4, help="Tensor parallel size for base model generation")
    parser.add_argument(
        "--base_gpus",
        type=str,
        default=None,
        help="Comma-separated GPU IDs to use for base generation only (overrides CUDA_VISIBLE_DEVICES during base generation)",
    )
    parser.add_argument("--temperature", type=float, default=0.1)
    parser.add_argument(
        "--base_temperature",
        type=float,
        default=None,
        help="Temperature for base model generation; defaults to --temperature if not set",
    )
    parser.add_argument(
        "--model_temperature",
        type=float,
        default=None,
        help="Temperature for checkpoint model generation; defaults to --temperature if not set",
    )
    parser.add_argument("--top_p", type=float, default=0.9)
    parser.add_argument("--start_idx", type=int, default=0)
    parser.add_argument("--end_idx", type=int, default=-1)

    # Judge
    parser.add_argument("--judge_model", type=str, required=True, help="Model id/path for the local judge LLM")
    parser.add_argument("--n_judge_samples", type=int, default=5)
    parser.add_argument("--judge_temperature", type=float, default=0.6, help="Sampling temperature for the judge model")
    parser.add_argument("--judge_top_p", type=float, default=0.95, help="Top-p nucleus sampling for the judge model")
    parser.add_argument("--judge_top_k", type=int, default=20, help="Top-k sampling value for the judge model")
    parser.add_argument("--judge_max_tokens", type=int, default=256, help="Maximum tokens generated by the judge model")
    parser.add_argument(
        "--switch_position",
        action="store_true",
        default=False,
        help="Also judge with responses swapped (B vs A) and reverse the resulting scores",
    )
    parser.add_argument(
        "--score_json_path",
        type=str,
        default=None,
        help="Optional explicit path for the JSON score summary",
    )

    # Scoring
    parser.add_argument("--beta", type=float, default=1.0)

    # Parallelism
    parser.add_argument(
        "--gpus",
        type=str,
        default=None,
        help="Comma-separated GPU IDs to use for parallel evaluation (e.g., '0,1,2,3'). If omitted, uses CUDA_VISIBLE_DEVICES or '0'",
    )
    parser.add_argument(
        "--worker_tp_size",
        type=int,
        default=1,
        help="Tensor parallel size per worker (must divide the number of provided GPUs)",
    )
    parser.add_argument(
        "--max_workers",
        type=int,
        default=None,
        help="Optional cap on concurrent workers (defaults to number of GPU groups)",
    )

    # Debug
    parser.add_argument("--max_prompts", type=int, default=None, help="Optional cap on number of unique prompts for testing")

    return parser.parse_args()


def get_message(instruction: str) -> List[Dict[str, str]]:
    return [{"role": "user", "content": instruction}]


def sanitize_model_name(model_id: str) -> str:
    return model_id.strip().replace("/", "__").replace(" ", "_")


def split_requirements_to_checks(dataset) -> "Dataset":
    from datasets import Dataset

    expanded = []
    for row in dataset:
        requirements_str: str = row.get("requirements", "")
        if not requirements_str:
            expanded.append({
                "prompt": row["prompt"],
                "requirements": requirements_str,
                "check": row["prompt"],
                "importance": None,
            })
            continue

        counter = 1
        parts: List[str] = []
        remaining = requirements_str
        while len(remaining) > 0:
            assert remaining.startswith(f"{counter})"), f"Malformed requirements at counter {counter}: {remaining[:80]}"
            needle = f"/100)\n{counter+1})"
            pos = remaining.find(needle)
            if pos > 0:
                curr = remaining[len(f"{counter})"):pos + len("/100)\n")]
            else:
                curr = remaining[len(f"{counter})"):]
            parts.append(curr)
            remaining = remaining[len(curr) + len(f"{counter})"):]
            counter += 1

        parts = list(map(lambda s: s.strip(), parts))
        for chunk in parts:
            base_fields = {
                "prompt": row["prompt"],
                "requirements": requirements_str,
            }
            if "(importance:" in chunk:
                check_text = chunk.split("(importance:")[0].strip()
                try:
                    importance_val = int(chunk.split("(importance:")[1].split("/")[0].strip())
                except Exception:
                    importance_val = None
                expanded.append({**base_fields, "check": check_text, "importance": importance_val})
            else:
                expanded.append({**base_fields, "check": chunk, "importance": None})

    return Dataset.from_list(expanded)


def load_preference_5score_template() -> str:
    template_path = Path(__file__).parent / "prompt_preference_5score.txt"
    with open(template_path, 'r') as f:
        return f.read()


def get_numeric_mode(values: List[int], score_range: Tuple[int, int]) -> Optional[int]:
    if not values:
        return None
    min_score, max_score = score_range
    filtered = [int(v) for v in values if min_score <= int(v) <= max_score]
    if not filtered:
        return None
    from collections import Counter

    counts = Counter(filtered)
    max_count = max(counts.values())
    modes = [k for k, v in counts.items() if v == max_count]
    modes.sort()
    return modes[len(modes) // 2]


class Preference5ScoreOutput:  # lightweight stand-in for pydantic BaseModel for JSON schema
    # We keep a local schema function to avoid importing pydantic at module import
    @staticmethod
    def model_json_schema() -> Dict[str, Any]:
        # Minimal JSON schema to guide vLLM structured decoding
        return {
            "$schema": "http://json-schema.org/draft-07/schema#",
            "type": "object",
            "properties": {
                "explanation": {"type": "string"},
                "verdict": {"type": "integer", "minimum": -1, "maximum": 4},
            },
            "required": ["verdict"],
            "additionalProperties": True,
        }


def get_guided_decoding_params():
    # Imported lazily to avoid GPU touching at module import
    from vllm.sampling_params import GuidedDecodingParams

    return GuidedDecodingParams(json=Preference5ScoreOutput.model_json_schema())


def is_valid_5score(value: Optional[int]) -> bool:
    try:
        if value is None:
            return False
        v = int(value)
        return -1 <= v <= 4
    except Exception:
        return False


def reverse_score_5score(score: int) -> int:
    if score == -1:
        return -1
    return 4 - int(score)


def parse_verdict_safely(text: str) -> Optional[int]:
    if not text:
        return None
    try:
        obj = json.loads(text)
        if isinstance(obj, dict):
            value = obj.get("verdict")
        else:
            value = obj
        if is_valid_5score(value):
            return int(value)
    except Exception:
        pass

    match = re.search(r"verdict\s*[:=]\s*([-]?\d)", text, flags=re.IGNORECASE)
    if match:
        try:
            cand = int(match.group(1))
            return cand if is_valid_5score(cand) else None
        except Exception:
            pass

    match = re.search(r"\b([-]?\d)\b", text)
    if match:
        try:
            cand = int(match.group(1))
            return cand if is_valid_5score(cand) else None
        except Exception:
            pass
    return None


def aggregate_numeric_samples(samples: List[int]) -> Tuple[Optional[float], Optional[int]]:
    parsed = [int(s) for s in samples if is_valid_5score(s)]
    if not parsed:
        return None, None
    valid_for_mean = [x for x in parsed if x != -1]
    mean_val = (sum(valid_for_mean) / len(valid_for_mean)) if valid_for_mean else None
    majority_val = get_numeric_mode(parsed, (0, 4))
    return mean_val, majority_val


def _collect_normalized_scores(value: Any) -> List[float]:
    if value is None:
        return []
    if isinstance(value, (list, tuple)):
        normalized: List[float] = []
        for item in value:
            normalized.extend(_collect_normalized_scores(item))
        return normalized
    try:
        return [float(value) / 4]
    except Exception:
        return []


def generate_n_responses(model_id: str, prompts: List[str], world_size: int, maxlen: int, n_response: int, temperature: float, top_p: float) -> List[List[str]]:
    print(f"Generating {n_response} responses per prompt with model: {model_id}")
    from transformers import AutoTokenizer
    from vllm import LLM, SamplingParams
    import torch
    from tqdm import tqdm

    tokenizer = AutoTokenizer.from_pretrained(model_id)
    llm = LLM(
        model=model_id,
        tensor_parallel_size=world_size,
        max_model_len=maxlen,
        gpu_memory_utilization=0.85,
        trust_remote_code=True,
    )
    chat_prompts = [tokenizer.apply_chat_template([{ "role": "user", "content": p }], tokenize=False, add_generation_prompt=True) for p in tqdm(prompts)]

    all_pass_outputs: List[List[str]] = []  # shape [n_response][num_prompts]
    for i in range(n_response):
        set_seed(i * 50)
        params = SamplingParams(
            temperature=temperature,
            top_p=top_p,
            max_tokens=maxlen,
            seed=i * 50,
        )
        outputs = llm.generate(chat_prompts, params)
        texts = [o.outputs[0].text for o in outputs]
        all_pass_outputs.append(texts)

    # transpose -> [num_prompts][n_response]
    per_prompt: List[List[str]] = []
    for idx in range(len(prompts)):
        per_prompt.append([all_pass_outputs[j][idx] for j in range(n_response)])
    del llm
    del tokenizer
    torch.cuda.empty_cache()
    return per_prompt


def add_static_response_columns(dataset, rows: List[dict], prompt_to_idx: Dict[str, int], base_resps: List[List[str]], model_resps: List[List[str]]):
    num_rows = len(rows)
    n_base = len(base_resps[0]) if base_resps else 0
    n_model = len(model_resps[0]) if model_resps else 0
    # Base responses
    for i in range(n_base):
        col = [base_resps[prompt_to_idx[rows[r]["prompt"]]][i] for r in range(num_rows)]
        dataset = dataset.add_column(f"base_response_{i}", col)
    # Model responses
    for j in range(n_model):
        col = [model_resps[prompt_to_idx[rows[r]["prompt"]]][j] for r in range(num_rows)]
        dataset = dataset.add_column(f"model_response_{j}", col)
    return dataset


def parse_preference_choice(s: str) -> Optional[str]:
    if s is None:
        return None
    t = s.strip()
    if not t:
        return None
    u = t.upper()
    if u in ("A", "B"):
        return u
    for ch in u:
        if ch in ("A", "B"):
            return ch
    return None


def aggregate_binary_choice(raw_samples: List[str]) -> Optional[str]:
    choices = [parse_preference_choice(s) for s in raw_samples if s is not None]
    choices = [c for c in choices if c in ("A", "B")]
    if not choices:
        return None
    from collections import Counter

    counts = Counter(choices)
    if counts.get("A", 0) > counts.get("B", 0):
        return "A"
    if counts.get("B", 0) > counts.get("A", 0):
        return "B"
    return None


def merge_dataset_results(dataset) -> "Dataset":
    from datasets import Dataset

    merged: Dict[str, dict] = {}
    for row in dataset:
        prompt = row["prompt"]
        if prompt not in merged:
            base_fields = {}
            for key, value in row.items():
                if key == "prompt" or key == "requirements" or key.startswith("base_response_") or key.startswith("model_response_"):
                    base_fields[key] = value
            for key in row.keys():
                if key.startswith("judge_") and (key.endswith("_majority") or key.endswith("_mean")):
                    base_fields[key] = []
            merged[prompt] = base_fields

        for key, value in row.items():
            if key.startswith("judge_") and (key.endswith("_majority") or key.endswith("_mean")):
                if key not in merged[prompt]:
                    merged[prompt][key] = []
                if value is not None:
                    merged[prompt][key].append(value)

    return Dataset.from_list(list(merged.values()))


def score_dataset(ds, beta: float) -> float:
    base_cols = sorted([c for c in ds.column_names if c.startswith("base_response_")], key=lambda x: int(x.split("_")[-1]))
    model_cols = sorted([c for c in ds.column_names if c.startswith("model_response_")], key=lambda x: int(x.split("_")[-1]))
    n_base = len(base_cols)
    n_model = len(model_cols)

    grouped: Dict[str, List[dict]] = {}
    for row in ds:
        p = row["prompt"]
        grouped.setdefault(p, []).append(row)

    prompt_vals: List[float] = []
    for p, rows in grouped.items():
        check_objectives: List[float] = []
        for row in rows:
            base_exp_terms: List[float] = []
            for b in range(n_base):
                vals: List[float] = []
                for a in range(n_model):
                    mean_key = f"judge_{a}_{b}_mean"
                    maj_key = f"judge_{a}_{b}_majority"
                    values = _collect_normalized_scores(row.get(mean_key, None))
                    if not values:
                        values = _collect_normalized_scores(row.get(maj_key, None))
                    if values:
                        vals.extend(values)
                if vals:
                    expected_score = sum(vals) / len(vals)
                    base_exp_terms.append(math.exp(-expected_score / beta))
            if not base_exp_terms:
                continue
            avg_exp = sum(base_exp_terms) / len(base_exp_terms)
            if avg_exp <= 0:
                continue
            check_objectives.append(-beta * math.log(avg_exp))
        if check_objectives:
            prompt_vals.append(min(check_objectives))

    if not prompt_vals:
        return float('nan')

    return sum(prompt_vals) / len(prompt_vals)


def _evaluate_single_checkpoint(model_id: str, gpu_group: str, args: argparse.Namespace, unique_prompts: List[str], prompt_to_idx: Dict[str, int], expanded_rows: List[dict], base_resps: List[List[str]]) -> Tuple[str, float]:
    # GPU binding is done in worker_main before any imports
    print(f"[Worker GPUs {gpu_group}] Evaluating {model_id}")

    try:
        from transformers import AutoTokenizer
        from vllm import LLM, SamplingParams
        import torch
        from datasets import Dataset

        # Generate candidate model responses on this worker's GPUs
        model_resps = generate_n_responses(
            model_id,
            unique_prompts,
            args.worker_tp_size,
            args.maxlen,
            args.n_response,
            args.model_temperature if args.model_temperature is not None else args.temperature,
            args.top_p,
        )

        # Instantiate judge
        judge_tokenizer = AutoTokenizer.from_pretrained(args.judge_model)
        judge_llm = LLM(
            model=args.judge_model,
            tensor_parallel_size=args.worker_tp_size,
            gpu_memory_utilization=0.85,
            trust_remote_code=True,
        )

        sampling_params = SamplingParams(
            temperature=args.judge_temperature,
            top_p=args.judge_top_p,
            top_k=args.judge_top_k,
            n=args.n_judge_samples,
            max_tokens=args.judge_max_tokens,
            guided_decoding=get_guided_decoding_params(),
        )

        num_rows = len(expanded_rows)
        n_base = len(base_resps[0]) if base_resps else 0
        n_model = len(model_resps[0]) if model_resps else 0

        mean_cols: Dict[Tuple[int, int], List[Optional[float]]] = {}
        maj_cols: Dict[Tuple[int, int], List[Optional[int]]] = {}
        for ai in range(n_model):
            for bj in range(n_base):
                mean_cols[(ai, bj)] = [None] * num_rows
                maj_cols[(ai, bj)] = [None] * num_rows

        template = load_preference_5score_template()

        for ai in range(n_model):
            for bj in range(n_base):
                rendered_prompts = []
                for row in expanded_rows:
                    p = row["prompt"]
                    check = row.get("check", p)
                    pid = prompt_to_idx[p]
                    a_text = model_resps[pid][ai]
                    b_text = base_resps[pid][bj]
                    instruction = template.format(prompt=p, response_a=a_text, response_b=b_text, check=check)
                    chat = get_message(instruction)
                    rendered_prompts.append(
                        judge_tokenizer.apply_chat_template(chat, tokenize=False, add_generation_prompt=True)
                    )

                response = judge_llm.generate(rendered_prompts, sampling_params)
                all_samples: List[List[int]] = []
                for result in response:
                    verdicts = [parse_verdict_safely(candidate.text) for candidate in result.outputs]
                    filtered = [int(v) for v in verdicts if is_valid_5score(v)]
                    all_samples.append(filtered)

                if args.switch_position:
                    rendered_switched = []
                    for row in expanded_rows:
                        p = row["prompt"]
                        check = row.get("check", p)
                        pid = prompt_to_idx[p]
                        a_text = base_resps[pid][bj]
                        b_text = model_resps[pid][ai]
                        instruction = template.format(prompt=p, response_a=a_text, response_b=b_text, check=check)
                        chat = get_message(instruction)
                        rendered_switched.append(
                            judge_tokenizer.apply_chat_template(chat, tokenize=False, add_generation_prompt=True)
                        )

                    response_switched = judge_llm.generate(rendered_switched, sampling_params)
                    for idx_row, result_switched in enumerate(response_switched):
                        verdicts = [parse_verdict_safely(candidate.text) for candidate in result_switched.outputs]
                        filtered = [int(v) for v in verdicts if is_valid_5score(v)]
                        reversed_scores = [reverse_score_5score(v) for v in filtered]
                        if idx_row < len(all_samples):
                            all_samples[idx_row].extend(reversed_scores)
                        else:
                            all_samples.append(reversed_scores)
                    del response_switched
                    torch.cuda.empty_cache()

                for row_idx, scores in enumerate(all_samples):
                    mean_val, maj_val = aggregate_numeric_samples(scores)
                    mean_cols[(ai, bj)][row_idx] = mean_val
                    maj_cols[(ai, bj)][row_idx] = maj_val

                del response
                torch.cuda.empty_cache()

        try:
            del judge_llm
        except Exception:
            pass
        try:
            del judge_tokenizer
        except Exception:
            pass
        torch.cuda.empty_cache()

        from datasets import Dataset

        ds = Dataset.from_list(expanded_rows)
        ds = add_static_response_columns(ds, expanded_rows, prompt_to_idx, base_resps, model_resps)
        for (ai, bj), col in maj_cols.items():
            ds = ds.add_column(f"judge_{ai}_{bj}_majority", col)
        for (ai, bj), col in mean_cols.items():
            ds = ds.add_column(f"judge_{ai}_{bj}_mean", col)

        result = score_dataset(ds, args.beta)

        # Push merged dataset to hub
        model_name_ = sanitize_model_name(model_id.split(":")[0])
        repo_id = f"{args.output_repo_prefix}_{model_name_}"
        ds_merged = merge_dataset_results(ds)
        try:
            print(f"[Worker GPUs {gpu_group}] Pushing merged results to {repo_id} ...")
            ds_merged.push_to_hub(repo_id)
        except Exception as push_exc:
            print(f"[Worker GPUs {gpu_group}] Push failed for {repo_id}: {push_exc}")

        print(f"[Worker GPUs {gpu_group}] Score for {model_id}: {result}")
        return sanitize_model_name(model_id.split(":")[0]), float(result)

    except Exception as e:
        print(f"[Worker GPUs {gpu_group}] ERROR evaluating {model_id}: {e}")
        return sanitize_model_name(model_id.split(":")[0]), float('nan')


def worker_main(gpu_group: str, args: argparse.Namespace, unique_prompts: List[str], prompt_to_idx: Dict[str, int], expanded_rows: List[dict], base_resps: List[List[str]], task_queue: "mp.Queue", result_queue: "mp.Queue"):
    # Bind GPUs for this worker process up-front, before any GPU library import
    os.environ["CUDA_VISIBLE_DEVICES"] = gpu_group
    while True:
        task = task_queue.get()
        if task is None:
            break
        idx, model_id = task
        name, score = _evaluate_single_checkpoint(model_id, gpu_group, args, unique_prompts, prompt_to_idx, expanded_rows, base_resps)
        result_queue.put((idx, name, score))


def parse_gpu_groups(gpus_arg: Optional[str], worker_tp_size: int) -> List[str]:
    # Determine list of GPUs to use
    if gpus_arg is None:
        env_gpus = os.environ.get("CUDA_VISIBLE_DEVICES")
        if env_gpus is not None and env_gpus.strip() != "":
            gpu_ids = [g.strip() for g in env_gpus.split(",") if g.strip() != ""]
        else:
            gpu_ids = ["0"]
    else:
        gpu_ids = [g.strip() for g in gpus_arg.split(",") if g.strip() != ""]

    if worker_tp_size <= 0:
        raise ValueError("--worker_tp_size must be >= 1")

    if len(gpu_ids) < worker_tp_size:
        raise ValueError("Number of GPUs provided is less than --worker_tp_size")

    if len(gpu_ids) % worker_tp_size != 0:
        raise ValueError("Number of GPUs must be divisible by --worker_tp_size")

    groups: List[str] = []
    for i in range(0, len(gpu_ids), worker_tp_size):
        groups.append(",".join(gpu_ids[i:i + worker_tp_size]))
    return groups


def main():
    st = time.time()
    args = parse_arguments()

    # Load dataset and expand to (prompt, check)
    from datasets import load_dataset, Dataset

    try:
        raw = load_dataset(args.dataset_repo, split='test')
    except Exception:
        raw = load_dataset(args.dataset_repo, split='train')
    if args.end_idx != -1:
        raw = raw.select(range(args.start_idx, min(args.end_idx, len(raw))))
    expanded = split_requirements_to_checks(raw)

    # Prepare unique prompts
    unique_prompts: List[str] = list(dict.fromkeys([row["prompt"] for row in expanded]))
    if args.max_prompts is not None:
        unique_prompts = unique_prompts[: args.max_prompts]
        expanded = Dataset.from_list([row for row in expanded if row["prompt"] in set(unique_prompts)])
    prompt_to_idx: Dict[str, int] = {p: i for i, p in enumerate(unique_prompts)}

    print(f"Num expanded rows (prompt, check): {len(expanded)}")
    print(f"Num unique prompts: {len(unique_prompts)}")

    # Generate base responses once (can use many GPUs via base_world_size)
    old_cvd = os.environ.get("CUDA_VISIBLE_DEVICES")
    try:
        if args.base_gpus is not None:
            base_gpu_str = ",".join([g.strip() for g in args.base_gpus.split(",") if g.strip() != ""])
            os.environ["CUDA_VISIBLE_DEVICES"] = base_gpu_str
            print(f"Using base GPUs: {base_gpu_str}")
        base_resps = generate_n_responses(
            args.base_model,
            unique_prompts,
            args.base_world_size,
            args.maxlen,
            args.n_response,
            args.base_temperature if args.base_temperature is not None else args.temperature,
            args.top_p,
        )
    finally:
        # Restore previous CUDA visibility for subsequent worker spawning
        if args.base_gpus is not None:
            if old_cvd is None:
                if "CUDA_VISIBLE_DEVICES" in os.environ:
                    del os.environ["CUDA_VISIBLE_DEVICES"]
            else:
                os.environ["CUDA_VISIBLE_DEVICES"] = old_cvd

    expanded_rows = [row for row in expanded]

    # Decide GPU groups and spawn workers
    groups = parse_gpu_groups(args.gpus, args.worker_tp_size)
    num_groups = len(groups)
    num_workers = num_groups if args.max_workers is None else min(num_groups, args.max_workers)
    print(f"Starting {num_workers} workers across GPU groups: {groups[:num_workers]}")

    ctx = mp.get_context("spawn")
    task_queue: "mp.Queue" = ctx.Queue()
    result_queue: "mp.Queue" = ctx.Queue()

    procs: List[mp.Process] = []
    for wi in range(num_workers):
        p = ctx.Process(
            target=worker_main,
            args=(groups[wi], args, unique_prompts, prompt_to_idx, expanded_rows, base_resps, task_queue, result_queue),
        )
        p.start()
        procs.append(p)

    # Enqueue tasks
    for idx, model_id in enumerate(args.check_points):
        task_queue.put((idx, model_id))
    # Sentinels
    for _ in range(num_workers):
        task_queue.put(None)

    # Collect results
    scores_accumulator: List[float] = []
    name_order: List[str] = []
    for _ in range(len(args.check_points)):
        idx, name, score = result_queue.get()
        scores_accumulator.append(score)
        name_order.append(name)

    # Join workers
    for p in procs:
        p.join()

    print(f"Done parallel evaluation. Total time: {time.time() - st:.2f}s")

    summary_path = Path(args.score_json_path) if args.score_json_path else Path(f"{sanitize_model_name(args.output_repo_prefix)}_scores.json")
    summary_data = {"checkpoints": args.check_points, "scores": scores_accumulator}
    with open(summary_path, "w") as f:
        json.dump(summary_data, f, indent=2)
    print(f"Saved score summary to {summary_path}")


if __name__ == "__main__":
    main()


